<a href="https://colab.research.google.com/github/JoshuaCora1806/mi-lab04-cs/blob/develop/LABORATORIO_04_MD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# LABORATORIO 4 - MINERÍA DE DATOS

## ACTIVIDAD A
Por medio de la librería ‘Pandas’, lea la base de datos, asigne nombres para las columnas, realice una imputación para la variable ‘Bare Nuclei’ por medio de la mediana y cambie las categorías para la variable ‘Class’ de 2 o 4 por 0 o 1

In [73]:
# Importar librerias
import pandas as pd

# Cargar datos desde el repositorio
url = 'https://archive.ics.uci.edu/static/public/15/data.csv'
df = pd.read_csv(url)
df.head()

,Sample_code_number,Clump_thickness,Uniformity_of_cell_size,Uniformity_of_cell_shape,Marginal_adhesion,Single_epithelial_cell_size,Bare_nuclei,Bland_chromatin,Normal_nucleoli,Mitoses,Class
0,1000025,5,1,1,1,2,1.0,3,1,1,2
1,1002945,5,4,4,5,7,10.0,3,2,1,2
2,1015425,3,1,1,1,2,2.0,3,1,1,2
3,1016277,6,8,8,1,3,4.0,3,7,1,2
4,1017023,4,1,1,3,2,1.0,3,1,1,2

In [74]:
# imputación para la variable ‘Bare Nuclei’ por medio de la mediana
med = df['Bare_nuclei'].median()
df['Bare_nuclei']=df['Bare_nuclei'].fillna(med)

# Nulos en Bare_nuclei
print("Nulos en Bare_nuclei:", df['Bare_nuclei'].isnull().sum())

Nulos en Bare_nuclei: 0

In [75]:
# cambiar las categorías para la variable ‘Class’ de 2 o 4 por 0 o 1
df['Class'] = df['Class'].replace({2: 0, 4: 1})
# Verificar resultados
print("Valores de 'Class':", df['Class'].unique())

Valores de 'Class': [0 1]

## ACTIVIDAD B
Realice una detección de valores atípicos univariados por medio del método del rango intercuartílico con 3 de longitud a la derecha y 3 a la izquierda, y elimínelos. Además, realice una detección de valores atípicos multivariados por medio de las distancias de Mahalanobis y elimine aquellos valores que superen el valor de 30.

### Eliminación de valores atípicos univariados

In [76]:
# Creamos una copia de la data
df1=df

# Detectar y eliminar outliers univariados con IQR * 3
for col in df1.select_dtypes(include='number').columns:
    Q1 = df1[col].quantile(0.25)
    Q3 = df1[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 3 * IQR
    upper_bound = Q3 + 3 * IQR
    df1 = df1[(df1[col] >= lower_bound) & (df1[col] <= upper_bound)]

In [77]:
# Metricas antes de la eliminación de outliers
df.describe()

,Sample_code_number,Clump_thickness,Uniformity_of_cell_size,Uniformity_of_cell_shape,Marginal_adhesion,Single_epithelial_cell_size,Bare_nuclei,Bland_chromatin,Normal_nucleoli,Mitoses,Class
count,6.990000e+02,699.000000,699.000000,699.000000,699.000000,699.000000,699.000000,699.000000,699.000000,699.000000,699.000000
mean,1.071704e+06,4.417740,3.134478,3.207439,2.806867,3.216023,3.486409,3.437768,2.866953,1.589413,0.344778
std,6.170957e+05,2.815741,3.051459,2.971913,2.855379,2.214300,3.621929,2.438364,3.053634,1.715078,0.475636
min,6.163400e+04,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
25%,8.706885e+05,2.000000,1.000000,1.000000,1.000000,2.000000,1.000000,2.000000,1.000000,1.000000,0.000000
50%,1.171710e+06,4.000000,1.000000,1.000000,1.000000,2.000000,1.000000,3.000000,1.000000,1.000000,0.000000
75%,1.238298e+06,6.000000,5.000000,5.000000,4.000000,4.000000,5.000000,5.000000,4.000000,1.000000,1.000000
max,1.345435e+07,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,1.000000

In [78]:
# Métricas luego de la eliminación de outliers
df1.describe()

,Sample_code_number,Clump_thickness,Uniformity_of_cell_size,Uniformity_of_cell_shape,Marginal_adhesion,Single_epithelial_cell_size,Bare_nuclei,Bland_chromatin,Normal_nucleoli,Mitoses,Class
count,4.430000e+02,443.000000,443.000000,443.000000,443.000000,443.000000,443.000000,443.000000,443.000000,443.0,443.0
mean,1.064794e+06,2.943567,1.304740,1.433409,1.347630,2.119639,1.295711,2.090293,1.266366,1.0,0.0
std,2.795542e+05,1.655642,0.892224,0.998625,0.979963,0.923131,1.053181,1.055462,1.007403,0.0,0.0
min,6.163400e+04,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,0.0
25%,1.002264e+06,1.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.0,0.0
50%,1.180523e+06,3.000000,1.000000,1.000000,1.000000,2.000000,1.000000,2.000000,1.000000,1.0,0.0
75%,1.256375e+06,4.000000,1.000000,1.000000,1.000000,2.000000,1.000000,3.000000,1.000000,1.0,0.0
max,1.371920e+06,8.000000,9.000000,8.000000,10.000000,10.000000,10.000000,7.000000,9.000000,1.0,0.0


### Eliminación de outliers multivariados usando mahalanobis

In [79]:
# Importamoslibrerias n
import numpy as np
from scipy.spatial.distance import mahalanobis
from numpy.linalg import pinv

In [80]:
# Variables numéricas
num_vars = df1.select_dtypes(include='number')

# Convertir a matriz
X = num_vars.values

In [81]:
# Media y matriz de covarianza inversa
mean_vec = np.mean(X, axis=0)
cov_matrix = np.cov(X, rowvar=False)
inv_cov_matrix = pinv(cov_matrix)

In [82]:
# Calcular distancias de Mahalanobis
mahal_dist = [mahalanobis(x, mean_vec, inv_cov_matrix) for x in X]

In [83]:
# Filtrar filas con distancia ≤ 30
df1['mahal_dist'] = mahal_dist
df1 = df1[df1['mahal_dist'] <= 30].drop(columns='mahal_dist')

## ACTIVIDAD C
Realice un cálculo de los principales estadísticos descriptivos para las variables predictoras y cree dos conjuntos de datos: uno en donde se aplique la transformación Z-score y otro en donde se aplique la normalización mín-máx, sobre todas las variables predictoras.

**"Class" es la variable opbjetivo, debido a que es la variable donde se define si el tumor es benigno o maligno**

In [84]:
from sklearn.preprocessing import StandardScaler

In [85]:
# Excluimos Clas para obtener las variables predictoras
y = df1.drop(columns=['Class'])
y.describe()

,Sample_code_number,Clump_thickness,Uniformity_of_cell_size,Uniformity_of_cell_shape,Marginal_adhesion,Single_epithelial_cell_size,Bare_nuclei,Bland_chromatin,Normal_nucleoli,Mitoses
count,4.430000e+02,443.000000,443.000000,443.000000,443.000000,443.000000,443.000000,443.000000,443.000000,443.0
mean,1.064794e+06,2.943567,1.304740,1.433409,1.347630,2.119639,1.295711,2.090293,1.266366,1.0
std,2.795542e+05,1.655642,0.892224,0.998625,0.979963,0.923131,1.053181,1.055462,1.007403,0.0
min,6.163400e+04,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0
25%,1.002264e+06,1.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.0
50%,1.180523e+06,3.000000,1.000000,1.000000,1.000000,2.000000,1.000000,2.000000,1.000000,1.0
75%,1.256375e+06,4.000000,1.000000,1.000000,1.000000,2.000000,1.000000,3.000000,1.000000,1.0
max,1.371920e+06,8.000000,9.000000,8.000000,10.000000,10.000000,10.000000,7.000000,9.000000,1.0

In [86]:
# Obtenemos el z_score
z_score_data = StandardScaler().fit_transform(y)

# Almacenamos en un df
df_zscore = pd.DataFrame(z_score_data, columns=y.columns)

# Principales estadísticos
df_zscore.describe()

,Sample_code_number,Clump_thickness,Uniformity_of_cell_size,Uniformity_of_cell_shape,Marginal_adhesion,Single_epithelial_cell_size,Bare_nuclei,Bland_chromatin,Normal_nucleoli,Mitoses
count,4.430000e+02,4.430000e+02,4.430000e+02,4.430000e+02,443.000000,4.430000e+02,443.000000,443.000000,4.430000e+02,443.0
mean,-3.528655e-16,-8.019670e-17,1.162852e-16,4.811802e-17,0.000000,-2.325704e-16,0.000000,0.000000,-6.415736e-17,0.0
std,1.001131e+00,1.001131e+00,1.001131e+00,1.001131e+00,1.001131,1.001131e+00,1.001131,1.001131,1.001131e+00,0.0
min,-3.592482e+00,-1.175232e+00,-3.419377e-01,-4.344959e-01,-0.355139,-1.214243e+00,-0.281096,-1.034169,-2.647071e-01,0.0
25%,-2.239269e-01,-1.175232e+00,-3.419377e-01,-4.344959e-01,-0.355139,-1.297477e-01,-0.281096,-1.034169,-2.647071e-01,0.0
50%,4.144466e-01,3.412404e-02,-3.419377e-01,-4.344959e-01,-0.355139,-1.297477e-01,-0.281096,-0.085645,-2.647071e-01,0.0
75%,6.860854e-01,6.388020e-01,-3.419377e-01,-4.344959e-01,-0.355139,-1.297477e-01,-0.281096,0.862878,-2.647071e-01,0.0
max,1.099871e+00,3.057514e+00,8.634559e+00,6.583066e+00,8.839262,8.546213e+00,8.274107,4.656971,7.685479e+00,0.0

In [89]:
from sklearn.preprocessing import MinMaxScaler

In [90]:
# Obtenemos la normalización min-max
minmax_data = MinMaxScaler().fit_transform(y)

# Convertir a DataFrame
df_minmax = pd.DataFrame(minmax_data, columns=y.columns)

# Principales estadísticos
df_minmax.describe()

,Sample_code_number,Clump_thickness,Uniformity_of_cell_size,Uniformity_of_cell_shape,Marginal_adhesion,Single_epithelial_cell_size,Bare_nuclei,Bland_chromatin,Normal_nucleoli,Mitoses
count,443.000000,443.000000,443.000000,443.000000,443.000000,443.000000,443.000000,443.000000,443.000000,443.0
mean,0.765603,0.277652,0.038093,0.061916,0.038626,0.124404,0.032857,0.181716,0.033296,0.0
std,0.213354,0.236520,0.111528,0.142661,0.108885,0.102570,0.117020,0.175910,0.125925,0.0
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
25%,0.717882,0.000000,0.000000,0.000000,0.000000,0.111111,0.000000,0.000000,0.000000,0.0
50%,0.853927,0.285714,0.000000,0.000000,0.000000,0.111111,0.000000,0.166667,0.000000,0.0
75%,0.911817,0.428571,0.000000,0.000000,0.000000,0.111111,0.000000,0.333333,0.000000,0.0
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0